# Generated by Django 4.2.9 on 2024-03-07 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LikesOpinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Лайкнутыее отзывы',
            },
        ),
        migrations.CreateModel(
            name='Opinions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opinion', models.CharField(max_length=300, verbose_name='Отзывы')),
                ('data_added', models.DateField()),
                ('likes', models.IntegerField(default=0, verbose_name='Лайки')),
            ],
            options={
                'verbose_name': 'Отзывы',
                'db_table': 'opinions',
            },
        ),
    ]
