# Generated by Django 5.0.6 on 2024-10-12 07:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(16), django.core.validators.MaxValueValidator(90)], verbose_name='Возраст'),
        ),
    ]
