# Generated by Django 5.0.6 on 2024-10-28 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default='+380 00 000 00 00', max_length=20, null=True, verbose_name='Телефон'),
        ),
    ]
