# Generated by Django 5.0.6 on 2024-10-05 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Opinions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opinion', models.CharField(max_length=300, verbose_name='Отзывы')),
                ('data_added', models.DateField()),
                ('likes', models.IntegerField(default=0, verbose_name='Лайки')),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.products', verbose_name='Товар')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Отзывы',
                'db_table': 'opinions',
            },
        ),
        migrations.CreateModel(
            name='LikesOpinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.products', verbose_name='Товар')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('opinion_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carts_products.opinions', verbose_name='Отзыв')),
            ],
            options={
                'verbose_name': 'Лайкнутыее отзывы',
            },
        ),
    ]
