# Generated by Django 4.2.9 on 2024-03-07 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main_favorite', '0001_initial'),
        ('carts_products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinions',
            name='id_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_favorite.products', verbose_name='Товар'),
        ),
    ]
