# Generated by Django 5.0.6 on 2024-10-17 10:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts_products', '0001_initial'),
        ('main', '0002_information'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LikesOpinion',
            new_name='LikesReviews',
        ),
        migrations.RenameModel(
            old_name='Opinions',
            new_name='Reviews',
        ),
        migrations.AlterModelOptions(
            name='likesreviews',
            options={'verbose_name': 'Лайкнутые отзывы'},
        ),
        migrations.RenameField(
            model_name='likesreviews',
            old_name='opinion_id',
            new_name='review_id',
        ),
        migrations.RenameField(
            model_name='reviews',
            old_name='opinion',
            new_name='review',
        ),
        migrations.AlterModelTable(
            name='reviews',
            table='review',
        ),
    ]
