# Generated by Django 4.2.9 on 2024-03-07 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=40, unique=True)),
                ('slug', models.SlugField(max_length=40, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Категорию',
                'db_table': 'category',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Избранные',
                'db_table': 'favorite',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_info', models.TextField()),
            ],
            options={
                'verbose_name': 'Информация',
                'db_table': 'information',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('slug', models.SlugField(max_length=100, null=True, unique=True, verbose_name='URL')),
                ('image', models.ImageField(upload_to='products/%Y/%m/%d/')),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('count_product', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('id_product', models.DecimalField(decimal_places=0, max_digits=7, null=True)),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='main_favorite.categories_product')),
            ],
            options={
                'verbose_name': 'Товары',
                'db_table': 'products',
                'ordering': ('id',),
            },
        ),
    ]
