# Generated by Django 5.0.6 on 2024-10-08 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_info', models.TextField()),
            ],
            options={
                'verbose_name': 'Информация',
                'db_table': 'information',
            },
        ),
    ]
